local L0_1, L1_1, L2_1
L0_1 = module
L1_1 = (...)
L2_1 = package
L2_1 = L2_1.seeall
L0_1(L1_1, L2_1)
L0_1 = require
L1_1 = "currencymanager"
L0_1 = L0_1(L1_1)
L1_1 = {}
L2_1 = {}
L2_1.tickerText = "Some investors give you a small loan of 1 million cookies. You open up a bakery across the street from Cafe Christie - one of the most popular bakeries in the world."
L1_1[1] = L2_1
L2_1 = {}
L2_1.tickerText = "People are coming from all over the street to see what all the fuss is about."
L1_1[3] = L2_1
L2_1 = {}
L2_1.tickerText = "Its been reported that there is a Baker at your bakery that is making the cookies."
L1_1[5] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie says you are no threat to their bakery. They will always be the top bakery."
L1_1[7] = L2_1
L2_1 = {}
L2_1.tickerText = "Someone stole a pastry from Cafe Christie. There are no known suspects at this time."
L1_1[9] = L2_1
L2_1 = {}
L2_1.tickerText = "The main suspect has been identified as you. They seem to be getting afraid of some competition."
L1_1[11] = L2_1
L2_1 = {}
L2_1.tickerText = "Things are getting serious. If found guilty, you will have to pay 2 cookies as compensation to Cafe Christie."
L1_1[13] = L2_1
L2_1 = {}
L2_1.tickerText = "The verdict is out. Cafe Christie will not be getting any compensation from you. They are pretty angry about this."
L1_1[15] = L2_1
L2_1 = {}
L2_1.tickerText = "There is a line up of people at your bakery. You must be doing something right."
L1_1[17] = L2_1
L2_1 = {}
L2_1.tickerText = "People are telling their friends about you. Word of mouth is working its magic."
L1_1[19] = L2_1
L2_1 = {}
L2_1.tickerText = "You're getting complaints about the quality of your food. People are complaining there aren't enough chocolate chips in their cookie."
L1_1[21] = L2_1
L2_1 = {}
L2_1.tickerText = "You hire a janitor. People are gross."
L1_1[23] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie seems to be sending in undercover customers to figure out why your bakery is so successful."
L1_1[25] = L2_1
L2_1 = {}
L2_1.tickerText = "Wow, Cafe Christie just changed their whole menu to match yours. You must be doing something right!"
L1_1[27] = L2_1
L2_1 = {}
L2_1.tickerText = "Your first casualty. A poor uncooked cookie fell on the floor and needed to be thrown out."
L1_1[29] = L2_1
L2_1 = {}
L2_1.tickerText = "It's time to get more funding to grow your bakery. Time to hit up Punchstarter and make a post."
L1_1[31] = L2_1
L2_1 = {}
L2_1.tickerText = "Your Punchstarter campaign isn't going to well. Only a few days left and you're not even half way funded."
L1_1[33] = L2_1
L2_1 = {}
L2_1.tickerText = "Success! Through some shady supporters, you manage to reach your target! Money is money!"
L1_1[35] = L2_1
L2_1 = {}
L2_1.tickerText = "Things are picking up so much that you can increase prices. Who says a monopoly is bad?"
L1_1[37] = L2_1
L2_1 = {}
L2_1.tickerText = "There are rumours going around that Cafe Christie is planning to break into your bakery at night and ruin the place. Stay alert. Stay safe."
L1_1[39] = L2_1
L2_1 = {}
L2_1.tickerText = "Phew! Nothing seems to be out of place. Guess they didn't break in after all!"
L1_1[41] = L2_1
L2_1 = {}
L2_1.tickerText = "Uh oh, your mixer doesn't seem to be working. Same with your oven. It can't be Cafe Christie, can it?"
L1_1[43] = L2_1
L2_1 = {}
L2_1.tickerText = "Those sneaky guys! Turns out they did break in and unplugged all your equipment. Maybe you should have checked to make sure it was plugged in before calling in professionals."
L1_1[45] = L2_1
L2_1 = {}
L2_1.tickerText = "Lots of people are coming in from nearby cities. Business is booming!"
L1_1[47] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie is losing business to you. They're getting pretty desperate to keep their customers. Keep an eye out for them...."
L1_1[49] = L2_1
L2_1 = {}
L2_1.tickerText = "There's a dog with a camera strapped to it's head walking around outside. Looks sketchy."
L1_1[51] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie is closed for some renovations. Who knows what the new place will look like!"
L1_1[52] = L2_1
L2_1 = {}
L2_1.tickerText = "They're open! And it looks exactly like your bakery! You get your legal team on the phone."
L1_1[53] = L2_1
L2_1 = {}
L2_1.tickerText = "You realize you don't have a legal team."
L1_1[54] = L2_1
L2_1 = {}
L2_1.tickerText = "You hire a legal team consisting of your old janitor that used to read law books for fun. Nobody said they had to be good."
L1_1[55] = L2_1
L2_1 = {}
L2_1.tickerText = "Somehow, you magically win in court! It's probably best not to tell people you bribed the judge with 2 for 1 coupons for cookies."
L1_1[56] = L2_1
L2_1 = {}
L2_1.tickerText = "Things are getting serious and business is booming - you need to buy the place next door and expand your bakery."
L1_1[57] = L2_1
L2_1 = {}
L2_1.tickerText = "Great! The place next door sold your their property. Time to begin renovations."
L1_1[59] = L2_1
L2_1 = {}
L2_1.tickerText = "Progress is going well. The construction is nearly done."
L1_1[61] = L2_1
L2_1 = {}
L2_1.tickerText = "It's open! Your new and improved bakery is open for business. Just in time too! You're getting people from all over the nation coming to visit."
L1_1[63] = L2_1
L2_1 = {}
L2_1.tickerText = "It's safe to say your bakery is a huge success. Everyone knows about you and it's always packed. What's next?"
L1_1[65] = L2_1
L2_1 = {}
L2_1.tickerText = "After a long nap, you decide that you want to be known as the best bakery in the world."
L1_1[67] = L2_1
L2_1 = {}
L2_1.tickerText = "You decide to launch some viral marketing videos with puppies and goats that have absolutely nothing to do with cookies or your bakery."
L1_1[69] = L2_1
L2_1 = {}
L2_1.tickerText = "Somehow, these videos are a huge success! You decide to get more videos made - this time with a talking sponge."
L1_1[71] = L2_1
L2_1 = {}
L2_1.tickerText = "Amazingly, people love talking sponges. People are weird."
L1_1[73] = L2_1
L2_1 = {}
L2_1.tickerText = "You're starting to become known across the continent. Things are looking great!"
L1_1[75] = L2_1
L2_1 = {}
L2_1.tickerText = "Meanwhile, Cafe Christie is losing even more business. They're getting even more desperate."
L1_1[77] = L2_1
L2_1 = {}
L2_1.tickerText = "Yikes! A wild monkey was let loose in your bakery and started eating all your cookies! You're not sure what to do about it."
L1_1[79] = L2_1
L2_1 = {}
L2_1.tickerText = "The wild monkey turns into a tourist attraction. You even buy him a big yellow hat to wear. He walks around eating cookies all day. What a good life."
L1_1[81] = L2_1
L2_1 = {}
L2_1.tickerText = "It turns out that Cafe Christie set that monkey loose to try and scare customers away. Looks like their plan backfired!"
L1_1[83] = L2_1
L2_1 = {}
L2_1.tickerText = "To take the next big leap and get more people, you need more stuff to sell other than just cookies. Time to research!"
L1_1[85] = L2_1
L2_1 = {}
L2_1.tickerText = "It turns out that people like dark cookies that look like they've been in the oven too long. You throw on some red chocolate chips and charge 5x as much."
L1_1[87] = L2_1
L2_1 = {}
L2_1.tickerText = "These new dark cookies are great! People are such suckers to pay extra for these cookies."
L1_1[89] = L2_1
L2_1 = {}
L2_1.tickerText = "People are starting to fly in from around the world to visit your bakery. All your hard work is paying off!"
L1_1[91] = L2_1
L2_1 = {}
L2_1.tickerText = "Uh oh, someone got sick from eating your rotten cookie. What did they think was going to happen?"
L1_1[93] = L2_1
L2_1 = {}
L2_1.tickerText = "One kid left upset because you didn't have a unicorn cookie. You tell your R&D team to look into it. Yes, you have a R&D team."
L1_1[95] = L2_1
L2_1 = {}
L2_1.tickerText = "You spared no expense when making this bakery. Except for the ingredients. Some of them are questionable."
L1_1[97] = L2_1
L2_1 = {}
L2_1.tickerText = "You start to take reservations. At this rate, it'll be by appointment only in no time!"
L1_1[99] = L2_1
L2_1 = {}
L2_1.tickerText = "The president visits your bakery. He says your cookies are 'meh'."
L1_1[101] = L2_1
L2_1 = {}
L2_1.tickerText = "You put up a big sign outside with the president's quote. This has got to help bring in more people."
L1_1[103] = L2_1
L2_1 = {}
L2_1.tickerText = "Strangely enough, the sign didn't help. Less people showed up. Live and learn!"
L1_1[105] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie is nearly out of business now. They're bringing out the big guns. A quad stacked, double glazed with sprinkles, limited time cookie. Uh oh."
L1_1[107] = L2_1
L2_1 = {}
L2_1.tickerText = "Hah, their quad stacked cookie is nothing. You decide to make an octo stacked cookie with triple glazed tops and whipped cream. That'll show them!"
L1_1[109] = L2_1
L2_1 = {}
L2_1.tickerText = "Some people are starting to complain that your cookies aren't healthy. You direct them straight to your flax and green tea cookies."
L1_1[111] = L2_1
L2_1 = {}
L2_1.tickerText = "You're nearly there. People are coming to your bakery from all corners of the planet. Success!"
L1_1[113] = L2_1
L2_1 = {}
L2_1.tickerText = "You decide to officially have your bakery declared a tourist attraction. Double dip and make more profit with all the souvenirs."
L1_1[115] = L2_1
L2_1 = {}
L2_1.tickerText = "You expand your lineup to include shirts, hats, pencils, backpacks, phone cases, car decals and more. People are loving this stuff."
L1_1[117] = L2_1
L2_1 = {}
L2_1.tickerText = "Sometimes you feel bad about how much people are spending at your bakery, but then you remember how rich you are and everything is fine."
L1_1[119] = L2_1
L2_1 = {}
L2_1.tickerText = "You did it! You have the most popular bakery in the world! Cafe Christie will be closing down soon. You finally beat them."
L1_1[121] = L2_1
L2_1 = {}
L2_1.tickerText = "Everything is going great! You're making bank and rolling in cookies. You even splurge on a coloured toilet paper with fancy designs. Life is good."
L1_1[123] = L2_1
L2_1 = {}
L2_1.tickerText = "Cafe Christie is now closed for business. Deep down, you kind of liked having a competitor around."
L1_1[125] = L2_1
L2_1 = {}
L2_1.tickerText = "People are starting to become addicted to your food. They literally can't get enough of it. If you can't keep up with demand, riots will break out."
L1_1[127] = L2_1
L2_1 = {}
L2_1.tickerText = "It's happening. Mobs of people are getting agressive because you can't keep up with cookie production. This could get ugly."
L1_1[129] = L2_1
L2_1 = {}
L2_1.tickerText = "Your popularity seems to be your downfall. Riots start to break out about who should get the last red velvet cookie. People are so impatient."
L1_1[131] = L2_1
L2_1 = {}
L2_1.tickerText = "Outsourcing! Your brilliant idea to solve this issue. Get your cookies made overseas and ship them to your bakery. Nobody will know they're not fresh."
L1_1[133] = L2_1
L2_1 = {}
L2_1.tickerText = "It turns out that people notice. The riots get even bigger. This is not what you wanted when you initially got your small loan of 1 million cookies."
L1_1[135] = L2_1
L2_1 = {}
L2_1.tickerText = "The government is stepping in. If you can't manage to produce enough cookies to keep people under control, they're going to shut you down. Yikes...."
L1_1[137] = L2_1
L2_1 = {}
L2_1.tickerText = "You have a solution! Use your savings to make a spaceship and fly it through a mystic portal that will take you back in time so you can prevent this from happening."
L1_1[139] = L2_1
L2_1 = {}
L2_1.tickerText = "Construction on your spaceship begins! Unfortunately, there isn't enough space to bring back anything with you (it's a very small ship)."
L1_1[141] = L2_1
L2_1 = {}
L2_1.tickerText = "It's made! Your spaceship engineers secretly stash something cool in the spaceship, but tell you not to look until you travel back in time. Uh, ok?"
L1_1[142] = L2_1
L2_1 = {}
L2_1.tickerText = "It's a really bumpy flight but you survive the flight through the portal! You're back to where you started with your 1 million cookie loan!"
L1_1[143] = L2_1
L2_1 = {}
L2_1.tickerText = "You decide to see what was hidden in your spaceship before take off. WOW, IT'S SWEET! It should really help you out when growing your bakery again."
L1_1[145] = L2_1
L2_1 = {}
L2_1.tickerText = "This time around, you know what to do and not mess up. Second time's a charm, right?"
L1_1[147] = L2_1
L2_1 = {}
L2_1.tickerText = "This time around, you know what to do and not mess up. Second time's a charm, right? D\195\169j\195\160 vu."
L1_1[149] = L2_1
L2_1 = {}
L2_1.tickerText = "It seems like you've messed with the game. We're on to you..."
L1_1[999999999] = L2_1

function L2_1()
  local L0_2, L1_2
  L0_2 = L1_1
  return L0_2
end

getNewsTable = L2_1

function L2_1()
  local L0_2, L1_2, L2_2
  L0_2 = L0_1
  L0_2 = L0_2.calculateBakeryPoints
  L0_2 = L0_2()
  L1_2 = 1
  while L0_2 > L1_2 do
    L1_2 = L1_2 + 1
    L2_2 = L1_1
    L2_2 = L2_2[L1_2]
    if L2_2 == nil then
      L1_2 = L1_2 + 1
    end
  end
  if 149 < L1_2 then
    L1_2 = 149
  end
  L2_2 = L1_1
  L2_2 = L2_2[L1_2]
  if L2_2 == nil then
    L2_2 = L1_1
    L2_2 = L2_2[999999999]
    return L2_2
  end
  L2_2 = L1_1
  L2_2 = L2_2[L1_2]
  return L2_2
end

getNews = L2_1
